project:
  name: @project.name@
  version: @project.version@

# Spring Boot configuration
spring:
  # Profiling
  profiles:
    active: development

  # Thymeleaf
  thymeleaf:
    mode: HTML
    cache: false

# Application settings
application:
  # Payment orders processing schedule
  processing.schedule: "0 0 18 * * MON-FRI"

# Logging settings
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    ROOT: INFO
    ru.philit.ufs: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.hazelcast: INFO

# Server configuration
server:
  port: 8085
  contextPath: /client
  session.timeout: 300
